'use client'

import { useRef, useState } from 'react'
import { ArrowLeft, Download, FileText, ImagePlus, Plus, Share2, Trash2, Upload, X } from 'lucide-react'
import type { DocumentCustomization } from '@/lib/document/types'
import type { TemplateId } from '@/lib/templates/registry'
import { downloadDocument, printDocument, shareDocument } from '@/lib/document/export'
import { InstantDocumentPreview } from '@/components/instant/InstantDocument'
import { InstantInvoice } from '@/components/instant/InstantInvoice'
import { INSTANT_MODES, instantDefaults, instantModeFromType, instantToDocument, isInstantReady, type InstantDocument, type InstantMode } from '@/lib/instant/types'

const input = (label: string, value: string | number, onChange: (value: string) => void, placeholder = '') => <label className="instant-field"><span>{label}</span><input value={value} placeholder={placeholder} onChange={event => onChange(event.target.value)} /></label>

export function InstantEditor({ initialMode, onBack, templateId, customization }: { initialMode: InstantMode; onBack: () => void; templateId: TemplateId; customization: DocumentCustomization }) {
  const [document, setDocument] = useState<InstantDocument>(() => instantDefaults(initialMode))
  const [message, setMessage] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const update = (patch: Partial<InstantDocument>) => setDocument(current => ({ ...current, ...patch }))
  const setMode = (mode: InstantMode) => setDocument(current => ({ ...current, mode, documentNumber: '' }))
  const updateItem = (id: string, patch: Partial<InstantDocument['items'][number]>) => update({ items: document.items.map(item => item.id === id ? { ...item, ...patch } : item) })
  const removeItem = (id: string) => update({ items: document.items.length === 1 ? document.items : document.items.filter(item => item.id !== id) })
  const action = async (fn: () => Promise<void>) => { setMessage('Preparing…'); try { await fn(); setMessage('Ready') } catch { setMessage('Could not complete that action') } }
  const ready = isInstantReady(document)
  const converted = instantToDocument(document)
  if (document.mode === 'invoice') return <div className="instant-shell"><header className="instant-header"><button className="icon-button" onClick={onBack} aria-label="Back"><ArrowLeft size={17} /></button><div><div className="eyebrow coral">KAGOJ INSTANT</div><h1>Create an invoice<span>.</span></h1></div><div className="instant-status"><span className="status-dot" /> Local draft</div></header><InstantInvoice document={document} setDocument={setDocument} onSave={() => action(async () => setMessage('Saved locally'))} onSend={() => action(async () => setMessage('Ready to send'))} onDownload={() => action(() => downloadDocument(converted, templateId, { ...customization, showLogo: Boolean(document.logoUrl), logoText: document.businessName }))} onPrint={() => printDocument()} onShare={() => action(() => shareDocument(converted, templateId, customization))} /></div>
  return <div className="instant-shell"><header className="instant-header"><button className="icon-button" onClick={onBack} aria-label="Back"><ArrowLeft size={17} /></button><div><div className="eyebrow coral">KAGOJ INSTANT</div><h1>{document.mode === 'payment' ? 'Confirm a payment' : `Create a ${document.mode}`}<span>.</span></h1></div><div className="instant-status"><span className="status-dot" /> Local draft</div></header>
    <div className="instant-mode-row">{INSTANT_MODES.map(mode => <button key={mode.id} className={document.mode === mode.id ? 'active' : ''} onClick={() => setMode(mode.id)}><b>{mode.label}</b><small>{mode.description}</small></button>)}</div>
    <div className="instant-layout"><section className="instant-form">
      <div className="instant-form-section"><div className="section-title"><span>01</span><div><b>Seller details</b><small>Start with your business identity.</small></div></div><div className="instant-logo-control"><div className="instant-logo-preview">{document.logoUrl ? <img src={document.logoUrl} alt="Logo preview" /> : <ImagePlus size={18} />}</div><div><b>{document.logoUrl ? 'Logo added' : 'Add a logo'}</b><small>Shown on the document</small></div><button type="button" className="mini-button" onClick={() => fileRef.current?.click()}><Upload size={13} /> Upload</button>{document.logoUrl && <button type="button" className="icon-button small" aria-label="Remove logo" onClick={() => update({ logoUrl: '' })}><X size={14} /></button>}<input ref={fileRef} hidden type="file" accept="image/*" onChange={event => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update({ logoUrl: String(reader.result) }); reader.readAsDataURL(file) }} /></div>{input('Business name', document.businessName, value => update({ businessName: value }), 'Your business name')}<div className="instant-fields-2">{input('Address', document.businessAddress, value => update({ businessAddress: value }), 'Dhaka, Bangladesh')}{input('Phone or email', document.businessPhone || document.businessEmail, value => update({ businessPhone: value }), 'Contact details')}</div></div>
      <div className="instant-form-section"><div className="section-title"><span>02</span><div><b>Customer & document</b><small>Only the details your customer needs.</small></div></div>{input('Customer name', document.customerName, value => update({ customerName: value }), 'e.g. Rahim Ahmed')}<div className="instant-fields-2">{input('Customer address', document.customerAddress, value => update({ customerAddress: value }), 'Optional address')}{input('Customer contact', document.customerPhone, value => update({ customerPhone: value }), 'Optional phone')}</div>{input('Ship to (optional)', document.shipToName, value => update({ shipToName: value }), 'Recipient name')}<div className="instant-fields-2">{input('Document number', document.documentNumber, value => update({ documentNumber: value }), 'INV-001')}{input('Date', document.date, value => update({ date: value }), 'YYYY-MM-DD')}</div>{document.mode === 'invoice' && input('Due date', document.dueDate, value => update({ dueDate: value }), 'Optional due date')}</div>
      <div className="instant-form-section"><div className="section-title"><span>03</span><div><b>Items & amount</b><small>Keep it clear and easy to scan.</small></div></div>{document.items.map((item, index) => <div className="instant-item" key={item.id}><div className="instant-item-top"><b>Item {index + 1}</b>{document.items.length > 1 && <button className="text-button" onClick={() => removeItem(item.id)}><Trash2 size={13} /> Remove</button>}</div>{input('Description', item.description, value => updateItem(item.id, { description: value }), 'Service or product')}<div className="instant-fields-2">{input('Quantity', item.quantity, value => updateItem(item.id, { quantity: Math.max(1, Number(value) || 1) }), '1')}{input('Unit price', item.unitPrice, value => updateItem(item.id, { unitPrice: Math.max(0, Number(value) || 0) }), '0')}</div></div>)}<button className="add-item-button" onClick={() => update({ items: [...document.items, { id: `instant-${Date.now()}`, description: '', quantity: 1, unitPrice: 0 }] })}><Plus size={14} /> Add line item</button><div className="instant-fields-2">{input('Discount', document.discount, value => update({ discount: Math.max(0, Number(value) || 0) }), '0')}{input('Delivery charge', document.deliveryCharge, value => update({ deliveryCharge: Math.max(0, Number(value) || 0) }), '0')}</div><div className="instant-fields-2">{input('Tax', document.tax, value => update({ tax: Math.max(0, Number(value) || 0) }), '0')}{input('Currency', document.currency, value => update({ currency: value === 'USD' || value === 'EUR' ? value : 'BDT' }), 'BDT')}</div></div>
      <div className="instant-form-section"><div className="section-title"><span>04</span><div><b>Payment & finishing touches</b><small>Make the next step obvious.</small></div></div><label className="instant-field"><span>Payment method</span><select value={document.paymentMethod} onChange={event => update({ paymentMethod: event.target.value as InstantDocument['paymentMethod'] })}>{['Cash', 'bKash', 'Nagad', 'Bank Transfer', 'Card'].map(method => <option key={method}>{method}</option>)}</select></label>{input('Reference', document.reference, value => update({ reference: value }), 'Transaction ID or reference')}{document.mode !== 'invoice' && input('Amount paid / received', document.amountPaid, value => update({ amountPaid: Math.max(0, Number(value) || 0) }), '0')}{input('Notes', document.notes, value => update({ notes: value }), 'Thank you for your business.')}{input('Terms', document.terms, value => update({ terms: value }), 'Payment due on receipt')}</div>
      <div className="instant-action-row"><button className="button primary" disabled={!ready} onClick={() => action(() => downloadDocument(converted, templateId, { ...customization, showLogo: Boolean(document.logoUrl), logoText: document.businessName }))}><Download size={15} /> Download PDF</button><button className="button outline" onClick={printDocument}><FileText size={15} /> Print</button><button className="button outline" disabled={!ready} onClick={() => action(() => shareDocument(converted, templateId, customization))}><Share2 size={15} /> Share</button></div>{!ready && <small className="instant-hint">Add a business name, customer, and one priced item to export.</small>}{message && <small className="instant-message">{message}</small>}
    </section><section className="instant-preview-stage"><div className="preview-label"><span>LIVE DOCUMENT</span><span><span className="save-dot" /> changes saved</span></div><InstantDocumentPreview document={document} onChange={update} /></section></div></div>
}
